/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { StatementsController } from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('StatementsController', () => {
  let controller : StatementsController;

  beforeAll(() => {
    controller = new StatementsController(testClient);
  });

  it('should Test GetStatements', async () => {
    const response = await makeApiCall(
      () => controller.getStatements(
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      'x-fapi-interaction-id': ['', false],
      'Content-Type': ['application/json; charset=utf-8', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
