/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data42, data42Schema } from './data42';
import { Links1, links1Schema } from './links1';
import { Meta, metaSchema } from './meta';

export interface AccountGETresponse1 {
  data: Data42;
  links: Links1;
  meta: Meta;
}

export const accountGETresponse1Schema: Schema<AccountGETresponse1> = object({
  data: ['Data', lazy(() => data42Schema)],
  links: ['Links', lazy(() => links1Schema)],
  meta: ['Meta', lazy(() => metaSchema)],
});
