/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import {
  AccountAccessConsentModel,
  accountAccessConsentModelSchema,
} from './accountAccessConsentModel';
import { Risk1, risk1Schema } from './risk1';

export interface AccountAccessConsent {
  data: AccountAccessConsentModel;
  risk: Risk1;
}

export const accountAccessConsentSchema: Schema<AccountAccessConsent> = object({
  data: ['Data', lazy(() => accountAccessConsentModelSchema)],
  risk: ['Risk', lazy(() => risk1Schema)],
});
