/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Consent1, consent1Schema } from './consent1';

export interface AccountAccessConsentModel {
  consent: Consent1;
}

export const accountAccessConsentModelSchema: Schema<AccountAccessConsentModel> = object(
  { consent: ['Consent', lazy(() => consent1Schema)] }
);
