/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Account3, account3Schema } from './account3';
import {
  AccountSubTypeEnum,
  accountSubTypeEnumSchema,
} from './accountSubTypeEnum';
import { AccountTypeEnum, accountTypeEnumSchema } from './accountTypeEnum';
import { Servicer2, servicer2Schema } from './servicer2';

export interface AccountModel {
  /** A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner. */
  accountId: string;
  /** Identification of the currency in which the account is held.  Usage: Currency should only be used in case one and the same account number covers several currencies and the initiating party needs to identify which currency needs to be used for settlement on the account. */
  currency: string;
  /** Specifies the type of account (personal or business). */
  accountType?: AccountTypeEnum;
  /** Specifies the sub type of account (product family group). */
  accountSubType?: AccountSubTypeEnum;
  /** Specifies the description of the account type. */
  description?: string;
  /** The nickname of the account, assigned by the account owner in order to provide an additional means of identification of the account. */
  nickname: string;
  account?: Account3;
  servicer?: Servicer2;
}

export const accountModelSchema: Schema<AccountModel> = object({
  accountId: ['AccountId', string()],
  currency: ['Currency', string()],
  accountType: ['AccountType', optional(accountTypeEnumSchema)],
  accountSubType: ['AccountSubType', optional(accountSubTypeEnumSchema)],
  description: ['Description', optional(string())],
  nickname: ['Nickname', string()],
  account: ['Account', optional(lazy(() => account3Schema))],
  servicer: ['Servicer', optional(lazy(() => servicer2Schema))],
});
