/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AccountSchemeModelEnum
 */
export enum AccountSchemeModelEnum {
  BECSElectronicCredit = 'BECSElectronicCredit',
  MaskedCardNumber = 'MaskedCardNumber',
}

/**
 * Schema for AccountSchemeModelEnum
 */
export const accountSchemeModelEnumSchema: Schema<AccountSchemeModelEnum> = stringEnum(
  AccountSchemeModelEnum
);
