/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data32, data32Schema } from './data32';
import { Links1, links1Schema } from './links1';
import { Meta, metaSchema } from './meta';

export interface AccountGETresponse {
  data: Data32;
  links: Links1;
  meta: Meta;
}

export const accountGETresponseSchema: Schema<AccountGETresponse> = object({
  data: ['Data', lazy(() => data32Schema)],
  links: ['Links', lazy(() => links1Schema)],
  meta: ['Meta', lazy(() => metaSchema)],
});
