/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import {
  AccountAccessConsentResponseModel,
  accountAccessConsentResponseModelSchema,
} from './accountAccessConsentResponseModel';
import { Links1, links1Schema } from './links1';
import { Meta, metaSchema } from './meta';
import { Risk1, risk1Schema } from './risk1';

export interface AccountAccessConsentPOSTresponse {
  data: AccountAccessConsentResponseModel;
  risk: Risk1;
  links: Links1;
  meta: Meta;
}

export const accountAccessConsentPOSTresponseSchema: Schema<AccountAccessConsentPOSTresponse> = object(
  {
    data: ['Data', lazy(() => accountAccessConsentResponseModelSchema)],
    risk: ['Risk', lazy(() => risk1Schema)],
    links: ['Links', lazy(() => links1Schema)],
    meta: ['Meta', lazy(() => metaSchema)],
  }
);
