/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AuthorisationTypeEnum
 */
export enum AuthorisationTypeEnum {
  Contactless = 'Contactless',
  None = 'None',
  PIN = 'PIN',
}

/**
 * Schema for AuthorisationTypeEnum
 */
export const authorisationTypeEnumSchema: Schema<AuthorisationTypeEnum> = stringEnum(
  AuthorisationTypeEnum
);
