/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data52, data52Schema } from './data52';
import { Links1, links1Schema } from './links1';
import { Meta, metaSchema } from './meta';

export interface BalancesGETresponse {
  data: Data52;
  links: Links1;
  meta: Meta;
}

export const balancesGETresponseSchema: Schema<BalancesGETresponse> = object({
  data: ['Data', lazy(() => data52Schema)],
  links: ['Links', lazy(() => links1Schema)],
  meta: ['Meta', lazy(() => metaSchema)],
});
