/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Set of elements used to fully identify the type of underlying transaction resulting in an entry. */
export interface BankTransactionCode {
  /** Specifies the family within a domain. */
  code: string;
  /** Specifies the sub-product family within a specific family. */
  subCode: string;
}

export const bankTransactionCodeSchema: Schema<BankTransactionCode> = object({
  code: ['Code', string()],
  subCode: ['SubCode', string()],
});
