/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data62, data62Schema } from './data62';
import { Links1, links1Schema } from './links1';
import { Meta, metaSchema } from './meta';

export interface BeneficiariesGETresponse {
  data: Data62;
  links: Links1;
  meta: Meta;
}

export const beneficiariesGETresponseSchema: Schema<BeneficiariesGETresponse> = object(
  {
    data: ['Data', lazy(() => data62Schema)],
    links: ['Links', lazy(() => links1Schema)],
    meta: ['Meta', lazy(() => metaSchema)],
  }
);
