/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CardSchemeNameEnum
 */
export enum CardSchemeNameEnum {
  AmericanExpress = 'AmericanExpress',
  Diners = 'Diners',
  Discover = 'Discover',
  MasterCard = 'MasterCard',
  VISA = 'VISA',
}

/**
 * Schema for CardSchemeNameEnum
 */
export const cardSchemeNameEnumSchema: Schema<CardSchemeNameEnum> = stringEnum(
  CardSchemeNameEnum
);
