/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CreditorReference {
  particulars?: string;
  code?: string;
  reference?: string;
}

export const creditorReferenceSchema: Schema<CreditorReference> = object({
  particulars: ['Particulars', optional(string())],
  code: ['Code', optional(string())],
  reference: ['Reference', optional(string())],
});
