/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CreditDebitIndicator3Enum
 */
export enum CreditDebitIndicator3Enum {
  Credit = 'Credit',
  Debit = 'Debit',
}

/**
 * Schema for CreditDebitIndicator3Enum
 */
export const creditDebitIndicator3EnumSchema: Schema<CreditDebitIndicator3Enum> = stringEnum(
  CreditDebitIndicator3Enum
);
