/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CreditDebitIndicatorEnum
 */
export enum CreditDebitIndicatorEnum {
  Credit = 'Credit',
  Debit = 'Debit',
}

/**
 * Schema for CreditDebitIndicatorEnum
 */
export const creditDebitIndicatorEnumSchema: Schema<CreditDebitIndicatorEnum> = stringEnum(
  CreditDebitIndicatorEnum
);
