/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { TransactionModel, transactionModelSchema } from './transactionModel';

export interface Data12 {
  /** Provides further details on an entry in the report. */
  transaction?: TransactionModel[];
}

export const data12Schema: Schema<Data12> = object({
  transaction: [
    'Transaction',
    optional(array(lazy(() => transactionModelSchema))),
  ],
});
