/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { OfferModel, offerModelSchema } from './offerModel';

export interface Data7 {
  offer?: OfferModel[];
}

export const data7Schema: Schema<Data7> = object({
  offer: ['Offer', optional(array(lazy(() => offerModelSchema)))],
});
