/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { PartyModel, partyModelSchema } from './partyModel';

export interface Data8 {
  party?: PartyModel;
}

export const data8Schema: Schema<Data8> = object({
  party: ['Party', optional(lazy(() => partyModelSchema))],
});
