/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Statement, statementSchema } from './statement';

export interface Data11 {
  statement?: Statement;
}

export const data11Schema: Schema<Data11> = object({
  statement: ['Statement', optional(lazy(() => statementSchema))],
});
