/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { BalanceModel, balanceModelSchema } from './balanceModel';

export interface Data52 {
  /** Balance */
  balance: BalanceModel[];
}

export const data52Schema: Schema<Data52> = object({
  balance: ['Balance', array(lazy(() => balanceModelSchema))],
});
