/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { DirectDebitModel, directDebitModelSchema } from './directDebitModel';

/** Data */
export interface Data5 {
  /** DirectDebit */
  directDebit?: DirectDebitModel[];
}

export const data5Schema: Schema<Data5> = object({
  directDebit: [
    'DirectDebit',
    optional(array(lazy(() => directDebitModelSchema))),
  ],
});
