/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  StandingOrderModel,
  standingOrderModelSchema,
} from './standingOrderModel';

/** Data */
export interface Data6 {
  /** StandingOrder */
  standingOrder?: StandingOrderModel[];
}

export const data6Schema: Schema<Data6> = object({
  standingOrder: [
    'StandingOrder',
    optional(array(lazy(() => standingOrderModelSchema))),
  ],
});
