/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { TransactionModel, transactionModelSchema } from './transactionModel';

export interface Data26 {
  /** Transaction */
  transaction?: TransactionModel[];
}

export const data26Schema: Schema<Data26> = object({
  transaction: [
    'Transaction',
    optional(array(lazy(() => transactionModelSchema))),
  ],
});
