/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { StatementModel, statementModelSchema } from './statementModel';

export interface Data21 {
  /** Provides further details on a statement. */
  statement?: StatementModel[];
}

export const data21Schema: Schema<Data21> = object({
  statement: ['Statement', optional(array(lazy(() => statementModelSchema)))],
});
