/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { AccountModel, accountModelSchema } from './accountModel';

/** Data */
export interface Data {
  /** Account */
  account?: AccountModel[];
}

export const dataSchema: Schema<Data> = object({
  account: ['Account', optional(array(lazy(() => accountModelSchema)))],
});
