/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  ScheduledPaymentModel,
  scheduledPaymentModelSchema,
} from './scheduledPaymentModel';

export interface Data9 {
  scheduledPayment?: ScheduledPaymentModel[];
}

export const data9Schema: Schema<Data9> = object({
  scheduledPayment: [
    'ScheduledPayment',
    optional(array(lazy(() => scheduledPaymentModelSchema))),
  ],
});
