/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DirectDebitStatusCodeEnum
 */
export enum DirectDebitStatusCodeEnum {
  Active = 'Active',
  Inactive = 'Inactive',
}

/**
 * Schema for DirectDebitStatusCodeEnum
 */
export const directDebitStatusCodeEnumSchema: Schema<DirectDebitStatusCodeEnum> = stringEnum(
  DirectDebitStatusCodeEnum
);
