/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Location of the end-user on the earth specified by two numbers representing vertical and horizontal position */
export interface GeoLocation {
  /** Latitude measured in decimal degress */
  latitude?: string;
  /** Longitude measured in decimal degress */
  longitude?: string;
}

export const geoLocationSchema: Schema<GeoLocation> = object({
  latitude: ['Latitude', optional(string())],
  longitude: ['Longitude', optional(string())],
});
