/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data10, data10Schema } from './data10';
import { Links1, links1Schema } from './links1';
import { Meta, metaSchema } from './meta';

export interface GetAccountStatementsResponse {
  data: Data10;
  links: Links1;
  meta: Meta;
}

export const getAccountStatementsResponseSchema: Schema<GetAccountStatementsResponse> = object(
  {
    data: ['Data', lazy(() => data10Schema)],
    links: ['Links', lazy(() => links1Schema)],
    meta: ['Meta', lazy(() => metaSchema)],
  }
);
