/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data7, data7Schema } from './data7';
import { Links1, links1Schema } from './links1';
import { Meta, metaSchema } from './meta';

export interface GetAccountOffersResponse {
  data: Data7;
  links: Links1;
  meta: Meta;
}

export const getAccountOffersResponseSchema: Schema<GetAccountOffersResponse> = object(
  {
    data: ['Data', lazy(() => data7Schema)],
    links: ['Links', lazy(() => links1Schema)],
    meta: ['Meta', lazy(() => metaSchema)],
  }
);
