/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data12, data12Schema } from './data12';
import { Links1, links1Schema } from './links1';
import { Meta, metaSchema } from './meta';

export interface GetAccountStatementTransactionsResponse {
  data: Data12;
  links: Links1;
  meta: Meta;
}

export const getAccountStatementTransactionsResponseSchema: Schema<GetAccountStatementTransactionsResponse> = object(
  {
    data: ['Data', lazy(() => data12Schema)],
    links: ['Links', lazy(() => links1Schema)],
    meta: ['Meta', lazy(() => metaSchema)],
  }
);
