/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data11, data11Schema } from './data11';
import { Links1, links1Schema } from './links1';
import { Meta, metaSchema } from './meta';

export interface GetAccountStatementResponse {
  data: Data11;
  links: Links1;
  meta: Meta;
}

export const getAccountStatementResponseSchema: Schema<GetAccountStatementResponse> = object(
  {
    data: ['Data', lazy(() => data11Schema)],
    links: ['Links', lazy(() => links1Schema)],
    meta: ['Meta', lazy(() => metaSchema)],
  }
);
