/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data8, data8Schema } from './data8';
import { Links1, links1Schema } from './links1';
import { Meta, metaSchema } from './meta';

export interface GetAccountPartyResponse {
  data: Data8;
  links: Links1;
  meta: Meta;
}

export const getAccountPartyResponseSchema: Schema<GetAccountPartyResponse> = object(
  {
    data: ['Data', lazy(() => data8Schema)],
    links: ['Links', lazy(() => links1Schema)],
    meta: ['Meta', lazy(() => metaSchema)],
  }
);
