/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data21, data21Schema } from './data21';
import { Links1, links1Schema } from './links1';
import { Meta, metaSchema } from './meta';

export interface GetStatementsResponse {
  data: Data21;
  links: Links1;
  meta: Meta;
}

export const getStatementsResponseSchema: Schema<GetStatementsResponse> = object(
  {
    data: ['Data', lazy(() => data21Schema)],
    links: ['Links', lazy(() => links1Schema)],
    meta: ['Meta', lazy(() => metaSchema)],
  }
);
