/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Amount of money of the cash balance after a transaction entry is applied to the account.. */
export interface InstructedAmount {
  /** A number of monetary units specified in an active currency where the unit of currency is explicit and compliant with ISO 4217. */
  amount: string;
  /** A code allocated to a currency by a Maintenance Agency under an international identification scheme, as described in the latest edition of the international standard ISO 4217 "Codes for the representation of currencies and funds". */
  currency: string;
}

export const instructedAmountSchema: Schema<InstructedAmount> = object({
  amount: ['Amount', string()],
  currency: ['Currency', string()],
});
