/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/**
 * Amount of money to be moved between the debtor and creditor, before deduction of charges, expressed in the currency as ordered by the initiating party.
 * Usage: This amount has to be transported unchanged through the transaction chain.
 */
export interface InstructedAmount1 {
  amount: string;
  /** A code allocated to a currency by a Maintenance Agency under an international identification scheme, as described in the latest edition of the international standard ISO 4217 "Codes for the representation of currencies and funds". */
  currency: string;
}

export const instructedAmount1Schema: Schema<InstructedAmount1> = object({
  amount: ['Amount', string()],
  currency: ['Currency', string()],
});
