/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Links relevant to the payload */
export interface Links {
  self: string;
  first?: string;
  prev?: string;
  next?: string;
  last?: string;
}

export const linksSchema: Schema<Links> = object({
  self: ['Self', string()],
  first: ['First', optional(string())],
  prev: ['Prev', optional(string())],
  next: ['Next', optional(string())],
  last: ['Last', optional(string())],
});
