/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface MerchantDetails2 {
  /** Name by which the merchant is known. */
  merchantName?: string;
  /** Category code conform to ISO 18245, related to the type of services or goods the merchant provides for the transaction. */
  merchantCategoryCode?: string;
}

export const merchantDetails2Schema: Schema<MerchantDetails2> = object({
  merchantName: ['MerchantName', optional(string())],
  merchantCategoryCode: ['MerchantCategoryCode', optional(string())],
});
