/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PartyTypeEnum
 */
export enum PartyTypeEnum {
  Delegate = 'Delegate',
  Joint = 'Joint',
  Sole = 'Sole',
}

/**
 * Schema for PartyTypeEnum
 */
export const partyTypeEnumSchema: Schema<PartyTypeEnum> = stringEnum(
  PartyTypeEnum
);
