/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PermissionEnum
 */
export enum PermissionEnum {
  ReadAccountsBasic = 'ReadAccountsBasic',
  ReadAccountsDetail = 'ReadAccountsDetail',
  ReadBalances = 'ReadBalances',
  ReadBeneficiariesBasic = 'ReadBeneficiariesBasic',
  ReadBeneficiariesDetail = 'ReadBeneficiariesDetail',
  ReadDirectDebits = 'ReadDirectDebits',
  ReadOffers = 'ReadOffers',
  ReadParty = 'ReadParty',
  ReadPartyAuthUser = 'ReadPartyAuthUser',
  ReadScheduledPaymentsBasic = 'ReadScheduledPaymentsBasic',
  ReadScheduledPaymentsDetail = 'ReadScheduledPaymentsDetail',
  ReadStandingOrdersBasic = 'ReadStandingOrdersBasic',
  ReadStandingOrdersDetail = 'ReadStandingOrdersDetail',
  ReadStatementsBasic = 'ReadStatementsBasic',
  ReadStatementsDetail = 'ReadStatementsDetail',
  ReadTransactionsBasic = 'ReadTransactionsBasic',
  ReadTransactionsCredits = 'ReadTransactionsCredits',
  ReadTransactionsDebits = 'ReadTransactionsDebits',
  ReadTransactionsDetail = 'ReadTransactionsDetail',
}

/**
 * Schema for PermissionEnum
 */
export const permissionEnumSchema: Schema<PermissionEnum> = stringEnum(
  PermissionEnum
);
