/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ProprietaryBankTransactionCode2 {
  /** Proprietary bank transaction code to identify the underlying transaction. */
  code: string;
  /** Identification of the issuer of the proprietary bank transaction code. */
  issuer?: string;
}

export const proprietaryBankTransactionCode2Schema: Schema<ProprietaryBankTransactionCode2> = object(
  { code: ['Code', string()], issuer: ['Issuer', optional(string())] }
);
