/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SchemeNameEnum
 */
export enum SchemeNameEnum {
  BICFI = 'BICFI',
}

/**
 * Schema for SchemeNameEnum
 */
export const schemeNameEnumSchema: Schema<SchemeNameEnum> = stringEnum(
  SchemeNameEnum
);
