/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ScheduledTypeEnum
 */
export enum ScheduledTypeEnum {
  Arrival = 'Arrival',
  Execution = 'Execution',
}

/**
 * Schema for ScheduledTypeEnum
 */
export const scheduledTypeEnumSchema: Schema<ScheduledTypeEnum> = stringEnum(
  ScheduledTypeEnum
);
