/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Party that manages the account on behalf of the account owner, that is manages the registration and booking of entries on the account, calculates balances on the account and provides information about the account. */
export interface Servicer {
  /** Name of the identification scheme, in a coded form as published in an external list. */
  schemeName: string;
  /** Unique and unambiguous identification of the servicing institution. */
  identification: string;
}

export const servicerSchema: Schema<Servicer> = object({
  schemeName: ['SchemeName', string()],
  identification: ['Identification', string()],
});
