/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for StandingOrderStatusCodeEnum
 */
export enum StandingOrderStatusCodeEnum {
  Active = 'Active',
  Inactive = 'Inactive',
}

/**
 * Schema for StandingOrderStatusCodeEnum
 */
export const standingOrderStatusCodeEnumSchema: Schema<StandingOrderStatusCodeEnum> = stringEnum(
  StandingOrderStatusCodeEnum
);
