/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data25, data25Schema } from './data25';
import { Links1, links1Schema } from './links1';
import { Meta, metaSchema } from './meta';

export interface StandingOrdersGETresponse {
  data: Data25;
  links: Links1;
  meta: Meta;
}

export const standingOrdersGETresponseSchema: Schema<StandingOrdersGETresponse> = object(
  {
    data: ['Data', lazy(() => data25Schema)],
    links: ['Links', lazy(() => links1Schema)],
    meta: ['Meta', lazy(() => metaSchema)],
  }
);
