/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Amount42, amount42Schema } from './amount42';
import { Type4Enum, type4EnumSchema } from './type4Enum';

/** Set of elements used to provide details of a benefit or reward amount for the statement resource. */
export interface StatementBenefit {
  amount: Amount42;
  /** Benefit type, in a coded form. */
  type: Type4Enum;
}

export const statementBenefitSchema: Schema<StatementBenefit> = object({
  amount: ['Amount', lazy(() => amount42Schema)],
  type: ['Type', type4EnumSchema],
});
