/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Amount42, amount42Schema } from './amount42';
import {
  CreditDebitIndicator3Enum,
  creditDebitIndicator3EnumSchema,
} from './creditDebitIndicator3Enum';
import { Type6Enum, type6EnumSchema } from './type6Enum';

/** Set of elements used to provide details of a generic interest amount related to the statement resource. */
export interface StatementInterest {
  amount: Amount42;
  /** Indicates whether the amount is a credit or a debit. Usage: A zero amount is considered to be a credit amount. */
  creditDebitIndicator: CreditDebitIndicator3Enum;
  /** Interest amount type, in a coded form. */
  type: Type6Enum;
}

export const statementInterestSchema: Schema<StatementInterest> = object({
  amount: ['Amount', lazy(() => amount42Schema)],
  creditDebitIndicator: [
    'CreditDebitIndicator',
    creditDebitIndicator3EnumSchema,
  ],
  type: ['Type', type6EnumSchema],
});
