/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data26, data26Schema } from './data26';
import { Links1, links1Schema } from './links1';
import { Meta, metaSchema } from './meta';

export interface TransactionsGETresponse {
  data: Data26;
  links: Links1;
  meta: Meta;
}

export const transactionsGETresponseSchema: Schema<TransactionsGETresponse> = object(
  {
    data: ['Data', lazy(() => data26Schema)],
    links: ['Links', lazy(() => links1Schema)],
    meta: ['Meta', lazy(() => metaSchema)],
  }
);
