/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type6Enum
 */
export enum Type6Enum {
  BalanceTransfer = 'BalanceTransfer',
  Cash = 'Cash',
  EstimatedNext = 'EstimatedNext',
  Purchase = 'Purchase',
  Total = 'Total',
}

/**
 * Schema for Type6Enum
 */
export const type6EnumSchema: Schema<Type6Enum> = stringEnum(Type6Enum);
