/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type7Enum
 */
export enum Type7Enum {
  BalanceTransferPromoEnd = 'BalanceTransferPromoEnd',
  DirectDebitDue = 'DirectDebitDue',
  LastPayment = 'LastPayment',
  LastStatement = 'LastStatement',
  NextStatement = 'NextStatement',
  PaymentDue = 'PaymentDue',
  PurchasePromoEnd = 'PurchasePromoEnd',
  StatementAvailable = 'StatementAvailable',
}

/**
 * Schema for Type7Enum
 */
export const type7EnumSchema: Schema<Type7Enum> = stringEnum(Type7Enum);
