/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type4Enum
 */
export enum Type4Enum {
  Cashback = 'Cashback',
  Insurance = 'Insurance',
  TravelDiscount = 'TravelDiscount',
  TravelInsurance = 'TravelInsurance',
}

/**
 * Schema for Type4Enum
 */
export const type4EnumSchema: Schema<Type4Enum> = stringEnum(Type4Enum);
