/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TypeEnum
 */
export enum TypeEnum {
  ClosingAvailable = 'ClosingAvailable',
  ClosingBooked = 'ClosingBooked',
  Expected = 'Expected',
  ForwardAvailable = 'ForwardAvailable',
  Information = 'Information',
  InterimAvailable = 'InterimAvailable',
  InterimBooked = 'InterimBooked',
  OpeningAvailable = 'OpeningAvailable',
  OpeningBooked = 'OpeningBooked',
  PreviouslyClosedBooked = 'PreviouslyClosedBooked',
}

/**
 * Schema for TypeEnum
 */
export const typeEnumSchema: Schema<TypeEnum> = stringEnum(TypeEnum);
