/**
 * Account and Transaction API SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type10Enum
 */
export enum Type10Enum {
  ArrearsClosingBalance = 'ArrearsClosingBalance',
  AvailableBalance = 'AvailableBalance',
  AverageBalanceWhenInCredit = 'AverageBalanceWhenInCredit',
  AverageBalanceWhenInDebit = 'AverageBalanceWhenInDebit',
  AverageDailyBalance = 'AverageDailyBalance',
  BalanceTransferClosingBalance = 'BalanceTransferClosingBalance',
  CashClosingBalance = 'CashClosingBalance',
  ClosingBalance = 'ClosingBalance',
  CreditLimit = 'CreditLimit',
  CurrentPayment = 'CurrentPayment',
  DirectDebitPaymentDue = 'DirectDebitPaymentDue',
  MinimumPaymentDue = 'MinimumPaymentDue',
  PreviousClosingBalance = 'PreviousClosingBalance',
  PreviousPayment = 'PreviousPayment',
  PurchaseClosingBalance = 'PurchaseClosingBalance',
  StartingBalance = 'StartingBalance',
  TotalAdjustments = 'TotalAdjustments',
  TotalCashAdvances = 'TotalCashAdvances',
  TotalCharges = 'TotalCharges',
  TotalCredits = 'TotalCredits',
  TotalDebits = 'TotalDebits',
  TotalPurchases = 'TotalPurchases',
}

/**
 * Schema for Type10Enum
 */
export const type10EnumSchema: Schema<Type10Enum> = stringEnum(Type10Enum);
