/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, unknown } from '../schema';
import { Data144, data144Schema } from './data144';
import { Links, linksSchema } from './links';
import { Risk48, risk48Schema } from './risk48';

export interface A2Createaccountrequest {
  data: Data144;
  risk: Risk48;
  links: Links;
  meta?: unknown;
}

export const a2CreateaccountrequestSchema: Schema<A2Createaccountrequest> = object(
  {
    data: ['Data', lazy(() => data144Schema)],
    risk: ['Risk', lazy(() => risk48Schema)],
    links: ['Links', lazy(() => linksSchema)],
    meta: ['Meta', unknown()],
  }
);
