/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface A8ExchangeauthorizationCodeforaccesstoken {
  accessToken: string;
  tokenType: string;
  refreshToken: string;
  expiresIn: number;
}

export const a8ExchangeauthorizationCodeforaccesstokenSchema: Schema<A8ExchangeauthorizationCodeforaccesstoken> = object(
  {
    accessToken: ['access_token', string()],
    tokenType: ['token_type', string()],
    refreshToken: ['refresh_token', string()],
    expiresIn: ['expires_in', number()],
  }
);
