/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, unknown } from '../schema';
import { Data10, data10Schema } from './data10';
import { Links, linksSchema } from './links';

export interface AC109Retrievebulkstatements2 {
  data: Data10;
  meta?: unknown;
  links: Links;
}

export const aC109Retrievebulkstatements2Schema: Schema<AC109Retrievebulkstatements2> = object(
  {
    data: ['Data', lazy(() => data10Schema)],
    meta: ['Meta', unknown()],
    links: ['Links', lazy(() => linksSchema)],
  }
);
