/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, unknown } from '../schema';
import { Data76, data76Schema } from './data76';
import { Links, linksSchema } from './links';

export interface AC103Retrievebulkbeneficiaries2 {
  data: Data76;
  meta?: unknown;
  links: Links;
}

export const aC103Retrievebulkbeneficiaries2Schema: Schema<AC103Retrievebulkbeneficiaries2> = object(
  {
    data: ['Data', lazy(() => data76Schema)],
    meta: ['Meta', unknown()],
    links: ['Links', lazy(() => linksSchema)],
  }
);
