/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, unknown } from '../schema';
import { Data79, data79Schema } from './data79';
import { Links, linksSchema } from './links';

export interface AC106Retrieveauthorisingparty2 {
  data: Data79;
  meta?: unknown;
  links: Links;
}

export const aC106Retrieveauthorisingparty2Schema: Schema<AC106Retrieveauthorisingparty2> = object(
  {
    data: ['Data', lazy(() => data79Schema)],
    meta: ['Meta', unknown()],
    links: ['Links', lazy(() => linksSchema)],
  }
);
