/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, unknown } from '../schema';
import { Data83, data83Schema } from './data83';
import { Links79, links79Schema } from './links79';

export interface AC1010Retrievebulktransactions2 {
  data: Data83;
  meta?: unknown;
  links: Links79;
}

export const aC1010Retrievebulktransactions2Schema: Schema<AC1010Retrievebulktransactions2> = object(
  {
    data: ['Data', lazy(() => data83Schema)],
    meta: ['Meta', unknown()],
    links: ['Links', lazy(() => links79Schema)],
  }
);
