/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, unknown } from '../schema';
import { Data84, data84Schema } from './data84';
import { Links70, links70Schema } from './links70';

export interface AC111Retrieveanaccount2 {
  data: Data84;
  links: Links70;
  meta?: unknown;
}

export const aC111Retrieveanaccount2Schema: Schema<AC111Retrieveanaccount2> = object(
  {
    data: ['Data', lazy(() => data84Schema)],
    links: ['Links', lazy(() => links70Schema)],
    meta: ['Meta', unknown()],
  }
);
