/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, unknown } from '../schema';
import { Data81, data81Schema } from './data81';
import { Links, linksSchema } from './links';

export interface AC118Retrieveaccountstandingorders2 {
  data: Data81;
  meta?: unknown;
  links: Links;
}

export const aC118Retrieveaccountstandingorders2Schema: Schema<AC118Retrieveaccountstandingorders2> = object(
  {
    data: ['Data', lazy(() => data81Schema)],
    meta: ['Meta', unknown()],
    links: ['Links', lazy(() => linksSchema)],
  }
);
