/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Account9, account9Schema } from './account9';
import { Servicer, servicerSchema } from './servicer';

export interface Account8 {
  accountId: string;
  currency: string;
  nickname: string;
  account: Account9;
  servicer: Servicer;
}

export const account8Schema: Schema<Account8> = object({
  accountId: ['AccountId', string()],
  currency: ['Currency', string()],
  nickname: ['Nickname', string()],
  account: ['Account', lazy(() => account9Schema)],
  servicer: ['Servicer', lazy(() => servicerSchema)],
});
