/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Account9 {
  identification: string;
  schemeName: string;
  name: string;
}

export const account9Schema: Schema<Account9> = object({
  identification: ['Identification', string()],
  schemeName: ['SchemeName', string()],
  name: ['Name', string()],
});
