/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

export interface ApproveCibaConsentAuthRequestIdRequest {
  accounts: string[];
}

export const approveCibaConsentAuthRequestIdRequestSchema: Schema<ApproveCibaConsentAuthRequestIdRequest> = object(
  { accounts: ['accounts', array(string())] }
);
