/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Amount, amountSchema } from './amount';

export interface Balance20 {
  accountId: string;
  amount: Amount;
  creditDebitIndicator: string;
  type: string;
  dateTime: string;
}

export const balance20Schema: Schema<Balance20> = object({
  accountId: ['AccountId', string()],
  amount: ['Amount', lazy(() => amountSchema)],
  creditDebitIndicator: ['CreditDebitIndicator', string()],
  type: ['Type', string()],
  dateTime: ['DateTime', string()],
});
