/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CreditorAccount41 {
  identification: string;
  schemeName: string;
  name: string;
  secondaryIdentification?: string;
}

export const creditorAccount41Schema: Schema<CreditorAccount41> = object({
  identification: ['Identification', string()],
  schemeName: ['SchemeName', string()],
  name: ['Name', string()],
  secondaryIdentification: ['SecondaryIdentification', optional(string())],
});
