/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Offer8, offer8Schema } from './offer8';

export interface Data150 {
  offer: Offer8[];
}

export const data150Schema: Schema<Data150> = object({
  offer: ['Offer', array(lazy(() => offer8Schema))],
});
