/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Initiation, initiationSchema } from './initiation';

export interface Data27 {
  initiation: Initiation;
  domesticPaymentId: string;
  statusUpdateDateTime: string;
  creationDateTime: string;
  consentId: string;
  status: string;
}

export const data27Schema: Schema<Data27> = object({
  initiation: ['Initiation', lazy(() => initiationSchema)],
  domesticPaymentId: ['DomesticPaymentId', string()],
  statusUpdateDateTime: ['StatusUpdateDateTime', string()],
  creationDateTime: ['CreationDateTime', string()],
  consentId: ['ConsentId', string()],
  status: ['Status', string()],
});
