/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

export interface Data144 {
  transactionToDateTime: string;
  transactionFromDateTime: string;
  permissions: string[];
  expirationDateTime: string;
  creationDateTime: string;
  statusUpdateDateTime: string;
  accountRequestId: string;
  status: string;
}

export const data144Schema: Schema<Data144> = object({
  transactionToDateTime: ['TransactionToDateTime', string()],
  transactionFromDateTime: ['TransactionFromDateTime', string()],
  permissions: ['Permissions', array(string())],
  expirationDateTime: ['ExpirationDateTime', string()],
  creationDateTime: ['CreationDateTime', string()],
  statusUpdateDateTime: ['StatusUpdateDateTime', string()],
  accountRequestId: ['AccountRequestId', string()],
  status: ['Status', string()],
});
