/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { StandingOrder8, standingOrder8Schema } from './standingOrder8';

export interface Data153 {
  standingOrder: StandingOrder8[];
}

export const data153Schema: Schema<Data153> = object({
  standingOrder: ['StandingOrder', array(lazy(() => standingOrder8Schema))],
});
