/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Consent5, consent5Schema } from './consent5';

export interface Data30 {
  consent: Consent5;
}

export const data30Schema: Schema<Data30> = object({
  consent: ['Consent', lazy(() => consent5Schema)],
});
