/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import {
  ScheduledPayment8,
  scheduledPayment8Schema,
} from './scheduledPayment8';

export interface Data152 {
  scheduledPayment: ScheduledPayment8[];
}

export const data152Schema: Schema<Data152> = object({
  scheduledPayment: [
    'ScheduledPayment',
    array(lazy(() => scheduledPayment8Schema)),
  ],
});
