/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Statement14, statement14Schema } from './statement14';

export interface Data166 {
  statement: Statement14[];
}

export const data166Schema: Schema<Data166> = object({
  statement: ['Statement', array(lazy(() => statement14Schema))],
});
