/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Party8, party8Schema } from './party8';

export interface Data151 {
  party: Party8;
}

export const data151Schema: Schema<Data151> = object({
  party: ['Party', lazy(() => party8Schema)],
});
