/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Account8, account8Schema } from './account8';

export interface Data74 {
  account: Account8[];
}

export const data74Schema: Schema<Data74> = object({
  account: ['Account', array(lazy(() => account8Schema))],
});
