/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Initiation16, initiation16Schema } from './initiation16';

export interface Data168 {
  initiation: Initiation16;
}

export const data168Schema: Schema<Data168> = object({
  initiation: ['Initiation', lazy(() => initiation16Schema)],
});
