/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { DebtorAccount, debtorAccountSchema } from './debtorAccount';

export interface Data101 {
  debtorAccount: DebtorAccount;
}

export const data101Schema: Schema<Data101> = object({
  debtorAccount: ['DebtorAccount', lazy(() => debtorAccountSchema)],
});
