/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Consent2, consent2Schema } from './consent2';

export interface Data25 {
  consent: Consent2;
  status: string;
  statusUpdateDateTime: string;
  creationDateTime: string;
  consentId: string;
}

export const data25Schema: Schema<Data25> = object({
  consent: ['Consent', lazy(() => consent2Schema)],
  status: ['Status', string()],
  statusUpdateDateTime: ['StatusUpdateDateTime', string()],
  creationDateTime: ['CreationDateTime', string()],
  consentId: ['ConsentId', string()],
});
