/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Party4, party4Schema } from './party4';

export interface Data79 {
  party: Party4;
}

export const data79Schema: Schema<Data79> = object({
  party: ['Party', lazy(() => party4Schema)],
});
