/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Consent2, consent2Schema } from './consent2';

export interface Data24 {
  consent: Consent2;
}

export const data24Schema: Schema<Data24> = object({
  consent: ['Consent', lazy(() => consent2Schema)],
});
