/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Transaction12, transaction12Schema } from './transaction12';

export interface Data155 {
  transaction: Transaction12[];
}

export const data155Schema: Schema<Data155> = object({
  transaction: ['Transaction', array(lazy(() => transaction12Schema))],
});
