/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Initiation16, initiation16Schema } from './initiation16';

export interface Data171 {
  initiation: Initiation16;
  creationDateTime: string;
  paymentId: string;
  status: string;
  paymentSubmissionId: string;
}

export const data171Schema: Schema<Data171> = object({
  initiation: ['Initiation', lazy(() => initiation16Schema)],
  creationDateTime: ['CreationDateTime', string()],
  paymentId: ['PaymentId', string()],
  status: ['Status', string()],
  paymentSubmissionId: ['PaymentSubmissionId', string()],
});
