/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Beneficiary4, beneficiary4Schema } from './beneficiary4';

export interface Data76 {
  beneficiary: Beneficiary4[];
}

export const data76Schema: Schema<Data76> = object({
  beneficiary: ['Beneficiary', array(lazy(() => beneficiary4Schema))],
});
