/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Balance20, balance20Schema } from './balance20';

export interface Data147 {
  balance: Balance20[];
}

export const data147Schema: Schema<Data147> = object({
  balance: ['Balance', array(lazy(() => balance20Schema))],
});
