/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Consent5, consent5Schema } from './consent5';

export interface Data31 {
  consent: Consent5;
  status: string;
  statusUpdateDateTime: string;
  creationDateTime: string;
  consentId: string;
}

export const data31Schema: Schema<Data31> = object({
  consent: ['Consent', lazy(() => consent5Schema)],
  status: ['Status', string()],
  statusUpdateDateTime: ['StatusUpdateDateTime', string()],
  creationDateTime: ['CreationDateTime', string()],
  consentId: ['ConsentId', string()],
});
