/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { DebtorAccount3, debtorAccount3Schema } from './debtorAccount3';

export interface Data29 {
  debtorAccount: DebtorAccount3;
}

export const data29Schema: Schema<Data29> = object({
  debtorAccount: ['DebtorAccount', lazy(() => debtorAccount3Schema)],
});
