/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Offer4, offer4Schema } from './offer4';

export interface Data78 {
  offer: Offer4[];
}

export const data78Schema: Schema<Data78> = object({
  offer: ['Offer', array(lazy(() => offer4Schema))],
});
