/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Transaction14, transaction14Schema } from './transaction14';

export interface Data167 {
  transaction: Transaction14[];
}

export const data167Schema: Schema<Data167> = object({
  transaction: ['Transaction', array(lazy(() => transaction14Schema))],
});
