/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { StandingOrder4, standingOrder4Schema } from './standingOrder4';

export interface Data81 {
  standingOrder: StandingOrder4[];
}

export const data81Schema: Schema<Data81> = object({
  standingOrder: ['StandingOrder', array(lazy(() => standingOrder4Schema))],
});
