/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Statement12, statement12Schema } from './statement12';

export interface Data154 {
  statement: Statement12[];
}

export const data154Schema: Schema<Data154> = object({
  statement: ['Statement', array(lazy(() => statement12Schema))],
});
