/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Transaction6, transaction6Schema } from './transaction6';

export interface Data83 {
  transaction: Transaction6[];
}

export const data83Schema: Schema<Data83> = object({
  transaction: ['Transaction', array(lazy(() => transaction6Schema))],
});
