/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface DFDP3V22Initiationbackchannelauthorisationrequestforadomesticpaymentconsent {
  authReqId: string;
  expiresIn: number;
  interval: number;
}

export const dFDP3V22InitiationbackchannelauthorisationrequestforadomesticpaymentconsentSchema: Schema<DFDP3V22Initiationbackchannelauthorisationrequestforadomesticpaymentconsent> = object(
  {
    authReqId: ['auth_req_id', string()],
    expiresIn: ['expires_in', number()],
    interval: ['interval', number()],
  }
);
