/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, unknown } from '../schema';
import { Data27, data27Schema } from './data27';
import { Links, linksSchema } from './links';
import { Risk2, risk2Schema } from './risk2';

export interface DP10Submitdomesticpayment {
  data: Data27;
  risk: Risk2;
  links: Links;
  meta?: unknown;
}

export const dP10SubmitdomesticpaymentSchema: Schema<DP10Submitdomesticpayment> = object(
  {
    data: ['Data', lazy(() => data27Schema)],
    risk: ['Risk', lazy(() => risk2Schema)],
    links: ['Links', lazy(() => linksSchema)],
    meta: ['Meta', unknown()],
  }
);
