/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, unknown } from '../schema';
import { Data101, data101Schema } from './data101';
import { Links, linksSchema } from './links';

export interface DP12Retrievesubmittedpaymentdebtoraccount2 {
  data: Data101;
  links: Links;
  meta?: unknown;
}

export const dP12Retrievesubmittedpaymentdebtoraccount2Schema: Schema<DP12Retrievesubmittedpaymentdebtoraccount2> = object(
  {
    data: ['Data', lazy(() => data101Schema)],
    links: ['Links', lazy(() => linksSchema)],
    meta: ['Meta', unknown()],
  }
);
