/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, unknown } from '../schema';
import { Data29, data29Schema } from './data29';
import { Links, linksSchema } from './links';

export interface DP12Retrievesubmittedpaymentdebtoraccount {
  data: Data29;
  links: Links;
  meta?: unknown;
}

export const dP12RetrievesubmittedpaymentdebtoraccountSchema: Schema<DP12Retrievesubmittedpaymentdebtoraccount> = object(
  {
    data: ['Data', lazy(() => data29Schema)],
    links: ['Links', lazy(() => linksSchema)],
    meta: ['Meta', unknown()],
  }
);
