/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, unknown } from '../schema';
import { Data25, data25Schema } from './data25';
import { Links, linksSchema } from './links';
import { Risk2, risk2Schema } from './risk2';

export interface DP2Createdomesticpaymentconsentresource {
  data: Data25;
  risk: Risk2;
  links: Links;
  meta?: unknown;
}

export const dP2CreatedomesticpaymentconsentresourceSchema: Schema<DP2Createdomesticpaymentconsentresource> = object(
  {
    data: ['Data', lazy(() => data25Schema)],
    risk: ['Risk', lazy(() => risk2Schema)],
    links: ['Links', lazy(() => linksSchema)],
    meta: ['Meta', unknown()],
  }
);
