/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, unknown } from '../schema';
import { Data25, data25Schema } from './data25';
import { Links, linksSchema } from './links';
import { Risk, riskSchema } from './risk';

export interface DP9Checkdomesticpaymentconsentstatus2 {
  data: Data25;
  risk: Risk;
  links: Links;
  meta?: unknown;
}

export const dP9Checkdomesticpaymentconsentstatus2Schema: Schema<DP9Checkdomesticpaymentconsentstatus2> = object(
  {
    data: ['Data', lazy(() => data25Schema)],
    risk: ['Risk', lazy(() => riskSchema)],
    links: ['Links', lazy(() => linksSchema)],
    meta: ['Meta', unknown()],
  }
);
