/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, unknown } from '../schema';
import { Data33, data33Schema } from './data33';
import { Links, linksSchema } from './links';
import { Risk2, risk2Schema } from './risk2';

export interface EP10Submitdomesticpayment {
  data: Data33;
  risk: Risk2;
  links: Links;
  meta?: unknown;
}

export const eP10SubmitdomesticpaymentSchema: Schema<EP10Submitdomesticpayment> = object(
  {
    data: ['Data', lazy(() => data33Schema)],
    risk: ['Risk', lazy(() => risk2Schema)],
    links: ['Links', lazy(() => linksSchema)],
    meta: ['Meta', unknown()],
  }
);
