/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data30, data30Schema } from './data30';
import { Risk2, risk2Schema } from './risk2';

export interface EP2CreateenduringpaymentconsentRequest {
  data: Data30;
  risk: Risk2;
}

export const eP2CreateenduringpaymentconsentRequestSchema: Schema<EP2CreateenduringpaymentconsentRequest> = object(
  {
    data: ['Data', lazy(() => data30Schema)],
    risk: ['Risk', lazy(() => risk2Schema)],
  }
);
