/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data30, data30Schema } from './data30';
import { Risk, riskSchema } from './risk';

export interface EP2CreateenduringpaymentconsentRequest2 {
  data: Data30;
  risk: Risk;
}

export const eP2CreateenduringpaymentconsentRequest2Schema: Schema<EP2CreateenduringpaymentconsentRequest2> = object(
  {
    data: ['Data', lazy(() => data30Schema)],
    risk: ['Risk', lazy(() => riskSchema)],
  }
);
