/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, unknown } from '../schema';
import { Data31, data31Schema } from './data31';
import { Links, linksSchema } from './links';
import { Risk, riskSchema } from './risk';

export interface EP9Checkenduringpaymentconsentstatus2 {
  data: Data31;
  risk: Risk;
  links: Links;
  meta?: unknown;
}

export const eP9Checkenduringpaymentconsentstatus2Schema: Schema<EP9Checkenduringpaymentconsentstatus2> = object(
  {
    data: ['Data', lazy(() => data31Schema)],
    risk: ['Risk', lazy(() => riskSchema)],
    links: ['Links', lazy(() => linksSchema)],
    meta: ['Meta', unknown()],
  }
);
