/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, unknown } from '../schema';
import { Data155, data155Schema } from './data155';
import { Links79, links79Schema } from './links79';

export interface ExampleA119Retrieveaccounttransactions {
  data: Data155;
  meta?: unknown;
  links: Links79;
}

export const exampleA119RetrieveaccounttransactionsSchema: Schema<ExampleA119Retrieveaccounttransactions> = object(
  {
    data: ['Data', lazy(() => data155Schema)],
    meta: ['Meta', unknown()],
    links: ['Links', lazy(() => links79Schema)],
  }
);
