/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, unknown } from '../schema';
import { Data152, data152Schema } from './data152';
import { Links, linksSchema } from './links';

export interface ExampleA117Retrieveaccountscheduledpayments {
  data: Data152;
  meta?: unknown;
  links: Links;
}

export const exampleA117RetrieveaccountscheduledpaymentsSchema: Schema<ExampleA117Retrieveaccountscheduledpayments> = object(
  {
    data: ['Data', lazy(() => data152Schema)],
    meta: ['Meta', unknown()],
    links: ['Links', lazy(() => linksSchema)],
  }
);
