/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, unknown } from '../schema';
import { Data147, data147Schema } from './data147';
import { Links, linksSchema } from './links';

export interface ExampleA112Retrieveaccountbalance {
  data: Data147;
  meta?: unknown;
  links: Links;
}

export const exampleA112RetrieveaccountbalanceSchema: Schema<ExampleA112Retrieveaccountbalance> = object(
  {
    data: ['Data', lazy(() => data147Schema)],
    meta: ['Meta', unknown()],
    links: ['Links', lazy(() => linksSchema)],
  }
);
