/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, unknown } from '../schema';
import { Data84, data84Schema } from './data84';
import { Links148, links148Schema } from './links148';

export interface ExampleA111Retrieveanaccount {
  data: Data84;
  links: Links148;
  meta?: unknown;
}

export const exampleA111RetrieveanaccountSchema: Schema<ExampleA111Retrieveanaccount> = object(
  {
    data: ['Data', lazy(() => data84Schema)],
    links: ['Links', lazy(() => links148Schema)],
    meta: ['Meta', unknown()],
  }
);
