/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, Schema, string } from '../schema';
import { TotalAmount, totalAmountSchema } from './totalAmount';

export interface Frequency {
  totalAmount: TotalAmount;
  period: string;
  totalCount: number;
}

export const frequencySchema: Schema<Frequency> = object({
  totalAmount: ['TotalAmount', lazy(() => totalAmountSchema)],
  period: ['Period', string()],
  totalCount: ['TotalCount', number()],
});
