/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface HFAC7Postconsentedaccountsarraytocompleteconsent {
  redirect: string;
}

export const hFAC7PostconsentedaccountsarraytocompleteconsentSchema: Schema<HFAC7Postconsentedaccountsarraytocompleteconsent> = object(
  { redirect: ['redirect', string()] }
);
