/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Links70 {
  self: string;
  payments: string;
}

export const links70Schema: Schema<Links70> = object({
  self: ['Self', string()],
  payments: ['Payments', string()],
});
