/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Links79 {
  self: string;
  next: string;
}

export const links79Schema: Schema<Links79> = object({
  self: ['Self', string()],
  next: ['Next', string()],
});
