/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Links148 {
  self: string;
  payment: string;
}

export const links148Schema: Schema<Links148> = object({
  self: ['Self', string()],
  payment: ['Payment', string()],
});
