/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface MaximumAmount {
  currency: string;
  amount: string;
}

export const maximumAmountSchema: Schema<MaximumAmount> = object({
  currency: ['Currency', string()],
  amount: ['Amount', string()],
});
