/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Offer8 {
  offerId: string;
  accountId: string;
}

export const offer8Schema: Schema<Offer8> = object({
  offerId: ['OfferId', string()],
  accountId: ['AccountId', string()],
});
