/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, unknown } from '../schema';
import { Data171, data171Schema } from './data171';
import { Links, linksSchema } from './links';

export interface P10Submitpayment {
  data: Data171;
  links: Links;
  meta?: unknown;
}

export const p10SubmitpaymentSchema: Schema<P10Submitpayment> = object({
  data: ['Data', lazy(() => data171Schema)],
  links: ['Links', lazy(() => linksSchema)],
  meta: ['Meta', unknown()],
});
