/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface P1Initiateclientcredentialsgrant {
  accessToken: string;
  tokenType: string;
  expiresIn: number;
}

export const p1InitiateclientcredentialsgrantSchema: Schema<P1Initiateclientcredentialsgrant> = object(
  {
    accessToken: ['access_token', string()],
    tokenType: ['token_type', string()],
    expiresIn: ['expires_in', number()],
  }
);
