/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data168, data168Schema } from './data168';
import { Risk48, risk48Schema } from './risk48';

export interface P2CreatepaymentRequest {
  data: Data168;
  risk: Risk48;
}

export const p2CreatepaymentRequestSchema: Schema<P2CreatepaymentRequest> = object(
  {
    data: ['Data', lazy(() => data168Schema)],
    risk: ['Risk', lazy(() => risk48Schema)],
  }
);
