/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, unknown } from '../schema';
import { Data169, data169Schema } from './data169';
import { Links, linksSchema } from './links';
import { Risk48, risk48Schema } from './risk48';

export interface P2Createpayment {
  data: Data169;
  risk: Risk48;
  links: Links;
  meta?: unknown;
}

export const p2CreatepaymentSchema: Schema<P2Createpayment> = object({
  data: ['Data', lazy(() => data169Schema)],
  risk: ['Risk', lazy(() => risk48Schema)],
  links: ['Links', lazy(() => linksSchema)],
  meta: ['Meta', unknown()],
});
