/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface P7Postconsentedaccounttocompleteconsent {
  redirect: string;
}

export const p7PostconsentedaccounttocompleteconsentSchema: Schema<P7Postconsentedaccounttocompleteconsent> = object(
  { redirect: ['redirect', string()] }
);
