/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { Address, addressSchema } from './address';

export interface Party4 {
  partyId: string;
  name: string;
  emailAddress: string;
  address: Address[];
}

export const party4Schema: Schema<Party4> = object({
  partyId: ['PartyId', string()],
  name: ['Name', string()],
  emailAddress: ['EmailAddress', string()],
  address: ['Address', array(lazy(() => addressSchema))],
});
