/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import {
  CreditorReference,
  creditorReferenceSchema,
} from './creditorReference';

export interface Reference6 {
  creditorReference: CreditorReference;
  creditorName: string;
}

export const reference6Schema: Schema<Reference6> = object({
  creditorReference: ['CreditorReference', lazy(() => creditorReferenceSchema)],
  creditorName: ['CreditorName', string()],
});
