/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { DeliveryAddress2, deliveryAddress2Schema } from './deliveryAddress2';
import { GeoLocation, geoLocationSchema } from './geoLocation';

export interface Risk2 {
  endUserAppName: string;
  endUserAppVersion: string;
  paymentContextCode: string;
  merchantName: string;
  merchantNZBN: string;
  merchantCategoryCode: string;
  merchantCustomerIdentification: string;
  geoLocation: GeoLocation;
  deliveryAddress: DeliveryAddress2;
}

export const risk2Schema: Schema<Risk2> = object({
  endUserAppName: ['EndUserAppName', string()],
  endUserAppVersion: ['EndUserAppVersion', string()],
  paymentContextCode: ['PaymentContextCode', string()],
  merchantName: ['MerchantName', string()],
  merchantNZBN: ['MerchantNZBN', string()],
  merchantCategoryCode: ['MerchantCategoryCode', string()],
  merchantCustomerIdentification: ['MerchantCustomerIdentification', string()],
  geoLocation: ['GeoLocation', lazy(() => geoLocationSchema)],
  deliveryAddress: ['DeliveryAddress', lazy(() => deliveryAddress2Schema)],
});
