/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { InstructedAmount, instructedAmountSchema } from './instructedAmount';

export interface ScheduledPayment8 {
  accountId: string;
  scheduledPaymentDateTime: string;
  scheduledType: string;
  instructedAmount: InstructedAmount;
}

export const scheduledPayment8Schema: Schema<ScheduledPayment8> = object({
  accountId: ['AccountId', string()],
  scheduledPaymentDateTime: ['ScheduledPaymentDateTime', string()],
  scheduledType: ['ScheduledType', string()],
  instructedAmount: ['InstructedAmount', lazy(() => instructedAmountSchema)],
});
