/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import {
  NextPaymentAmount,
  nextPaymentAmountSchema,
} from './nextPaymentAmount';

export interface StandingOrder8 {
  accountId: string;
  standingOrderId: string;
  frequency: string;
  nextPaymentDateTime: string;
  nextPaymentAmount: NextPaymentAmount;
}

export const standingOrder8Schema: Schema<StandingOrder8> = object({
  accountId: ['AccountId', string()],
  standingOrderId: ['StandingOrderId', string()],
  frequency: ['Frequency', string()],
  nextPaymentDateTime: ['NextPaymentDateTime', string()],
  nextPaymentAmount: ['NextPaymentAmount', lazy(() => nextPaymentAmountSchema)],
});
