/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { StatementAmount, statementAmountSchema } from './statementAmount';

export interface Statement14 {
  accountId: string;
  statementId: string;
  startDateTime: string;
  endDateTime: string;
  creationDateTime: string;
  statementAmount: StatementAmount[];
  type: string;
}

export const statement14Schema: Schema<Statement14> = object({
  accountId: ['AccountId', string()],
  statementId: ['StatementId', string()],
  startDateTime: ['StartDateTime', string()],
  endDateTime: ['EndDateTime', string()],
  creationDateTime: ['CreationDateTime', string()],
  statementAmount: [
    'StatementAmount',
    array(lazy(() => statementAmountSchema)),
  ],
  type: ['Type', string()],
});
