/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Statement12 {
  accountId: string;
  statementId: string;
  startDateTime: string;
  endDateTime: string;
  creationDateTime: string;
  type: string;
}

export const statement12Schema: Schema<Statement12> = object({
  accountId: ['AccountId', string()],
  statementId: ['StatementId', string()],
  startDateTime: ['StartDateTime', string()],
  endDateTime: ['EndDateTime', string()],
  creationDateTime: ['CreationDateTime', string()],
  type: ['Type', string()],
});
