/**
 * Account information PNZ-API-CentreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface TotalAmount {
  currency: string;
  amount: string;
}

export const totalAmountSchema: Schema<TotalAmount> = object({
  currency: ['Currency', string()],
  amount: ['Amount', string()],
});
